apiVersion: v1
kind: Service
metadata:
  name: {{ include "rafterFrontmatterService.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "rafterFrontmatterService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rafterFrontmatterService.chart" . }}
  {{- if .Values.service.labels }}
    {{ include "rafterFrontmatterService.tplValue" ( dict "value" .Values.metrics.service.labels "context" . ) | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ include "rafterFrontmatterService.tplValue" ( dict "value" .Values.metrics.service.annotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.port.name }}
      port: {{ .Values.service.port.external }}
      protocol: {{ .Values.service.port.protocol }}
      targetPort: {{ .Values.service.port.internal }}
  selector:
    app.kubernetes.io/name: {{ include "rafterFrontmatterService.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
